<?php
/**
 * Created by wplaat (Plaatsoft)
 *
 * This software is open source and may be copied, distributed or modified under the terms of the GNU General Public License (GPL) Version 2
 *
 * For more information visit the following website.
 * Website : http://www.plaatsoft.nl 
 *
 * Or send an email to the following address.
 * Email   : info@plaatsoft.nl
 */

include("utils.php"); 
include("database.php"); 

// Oostpoort module URLs
define('OOSTPOORT_MENU',            'base');

define('OOSTPOORT_FAMILY_LIST',     'family/list');
define('OOSTPOORT_FAMILY_VIEW',     'family/view');
define('OOSTPOORT_FAMILY_MAP',      'family/map');
define('OOSTPOORT_FAMILY_BLOCK',    'family/block');

define('OOSTPOORT_JUBILEA_BIRTHDAY','jubilea/birthday');
define('OOSTPOORT_JUBILEA_MARRIED', 'jubilea/married');

define('OOSTPOORT_UPLOAD',          'member/upload');
define('OOSTPOORT_MEMBER_AGE',      'member/age');
define('OOSTPOORT_MEMBER_VIEW',     'member/view');

define('OOSTPOORT_PICTURE_VIEW',    'picture/view');
define('OOSTPOORT_PICTURE_EDIT',    'picture/edit');

define('OOSTPOORT_IMAGE_DIR',       'files/oostpoort');
define('OOSTPOORT_THUMBNAILS_DIR',  'files/oostpoort/thumbnails');

/**
 * help hook()
 * @return help texts
 */
function oostpoort_help($section) {

  $output = '';
  switch ($section) {
    case 'admin/modules#description':
      $output .= t('Oostpoort leden administratie module');
      break;
  }
  return $output;
}

/**
 * menu hook()
 * @return array of menu items
 */
function oostpoort_menu() {

  $items = array();

  $items[] = array('path' =>  OOSTPOORT_MENU,
                   'title' => t('Oostpoort Menu'),
                   'callback' => 'oostpoort_base',
                   'access' => user_access('view address'),
                   'type' => MENU_CALLBACK);

  $items[] = array('path' =>  OOSTPOORT_UPLOAD,
                   'title' => t('Oostpoort CSV upload'),
                   'callback' => 'oostpoort_upload_csv',
                   'access' => user_access('add address'),
                   'type' => MENU_CALLBACK);

  $items[] = array('path' =>  OOSTPOORT_FAMILY_LIST,
                   'title' => t('Oostpoort familie lijst'),
                   'callback' => 'oostpoort_family_list',
                   'access' => user_access('view address'),
                   'type' => MENU_CALLBACK);

  $items[] = array('path' =>  OOSTPOORT_FAMILY_VIEW,
                   'title' => t('Oostpoort familie details'),
                   'callback' => 'oostpoort_family_view',
                   'access' => user_access('view address'),
                   'type' => MENU_CALLBACK);

  $items[] = array('path' => OOSTPOORT_FAMILY_MAP,
                   'title' => t('Oostpoort kaart bekijken'),
                   'callback' => 'oostpoort_family_map',
                   'access' => user_access('view address'),
                   'type' => MENU_CALLBACK);

  $items[] = array('path' =>  OOSTPOORT_MEMBER_AGE,
                   'title' => t('Oostpoort ledenlijst leeftijd'),
                   'callback' => 'oostpoort_member_age',
                   'access' => user_access('view address'),
                   'type' => MENU_CALLBACK);

  $items[] = array('path' =>  OOSTPOORT_FAMILY_BLOCK,
                   'title' => t('Oostpoort familie blok'),
                   'callback' => 'oostpoort_family_block',
                   'access' => user_access('view address'),
                   'type' => MENU_CALLBACK);

  $items[] = array('path' =>  OOSTPOORT_MEMBER_VIEW,
                   'title' => t('Oostpoort lid details'),
                   'callback' => 'oostpoort_member_view',
                   'access' => user_access('view address'),
                   'type' => MENU_CALLBACK);

  $items[] = array('path' =>  OOSTPOORT_JUBILEA_BIRTHDAY,
                   'title' => t('Oostpoort jubilea verjaarday'),
                   'callback' => 'oostpoort_jubilea_birthday',
                   'access' => user_access('view address'),
                   'type' => MENU_CALLBACK);

  $items[] = array('path' =>  OOSTPOORT_JUBILEA_MARRIED,
                   'title' => t('Oostpoort jubilea huwelijk'),
                   'callback' => 'oostpoort_jubilea_married',
                   'access' => user_access('view address'),
                   'type' => MENU_CALLBACK);

  $items[] = array('path' => OOSTPOORT_PICTURE_VIEW,
                   'title' => t('Oostpoort foto bekijken'),
                   'callback' => 'oostpoort_picture_view',
                   'access' => user_access('view address'),
                   'type' => MENU_CALLBACK);

  $items[] = array('path' => OOSTPOORT_PICTURE_EDIT,
                   'title' => t('Oostpoort foto uploaden'),
                   'callback' => 'oostpoort_picture_edit',
                   'access' => user_access('add address'),
                   'type' => MENU_CALLBACK);

  $items[] = array('path' => 'admin/settings/oostpoort',
                   'title' => t('Oostpoort'),
                   'description' => t('Instellingen Oostpoort leden administratie module.'),
                   'callback' => 'drupal_get_form',
                   'callback arguments' => array('oostpoort_settings'),
                   'access' => user_access('administer site configuration'),
                   'type' => MENU_NORMAL_ITEM);

  return $items;
}

/**
  * Valid permisions for this module
  * @return array an array of valid permission for the module
  */
function oostpoort_perm() 
{
  return array('view address','edit address', 'view all');
}

/**
 * Module configuration settings
 * @return settings HTML or deny access
 */
function oostpoort_settings() {

 //only administrators can access this module
 if (!user_access('access administration pages')) 
 {
    return drupal_access_denied();
 }

 $form['settings_general'] = array('#type' => 'fieldset', '#title' => t('General settings'));

 $form['settings_general']['oostpoort_roles'] = array(
     '#type' => 'textarea',
     '#title' => t('Roles'),
     '#default_value' => variable_get('oostpoort_roles', ''),
     '#rows' => 1,
     '#description' => t("Enter roles with a person can have (Seperated items with commas. No space allowed).") );

  $form['map24'] = array('#type' => 'fieldset', '#title' => t('Map settings'));

  $form['map24']['addressbook_map_link'] = array(
     '#type' => 'select',
     '#title' => t('Activate map link'),
     '#default_value' => variable_get('addressbook_map_link',0),
     '#options' => array( 0 => t('No'), 1 => t('Yes') ),
     '#description' => t('Enable / Disable Activate www.map24.com fast link.'));

  $form['map24']['addressbook_map_key'] = array(
     '#type' => 'textfield',
     '#title' => t('Free www.map24.com access key'),
     '#default_value' => variable_get('addressbook_map_key', ''),
     '#description' => t("Enter access key (Visit http://www.map24.com to get a free key)"),
     '#maxlength' => '50',
     '#size' => '50');

  return system_settings_form($form);
}

// ##################################################################################
// MODULE MAIN MENU
// ##################################################################################

function oostpoort_base( ) 
{
  global $user;

  // key to encrypt crc checksum
  //oostpoort_makeCksum();

  // Breadcrumb menu
  $page  = '<div class="breadcrumb">';
  $page .= '<a href="'.url("").'">Home</a> > ';
  $page .= 'Menu';
  $page .= '</div>';

  $page .= '<div class="oostpoort">';

  drupal_set_title(t('Oostpoort Menu'));

  $page .= '<br/>';

  $page .= '<div class="admin-panel">';
  $page .= '<H3>';
  $page .= 'Keuze menu';
  $page .= '</H3>';
  $page .= '<div class="body">';
  $page .= '<p class="description">';
  $page .= 'Alle getoonde informatie (die niet aangepast kan worden) is afkomstig van het kerkelijk bureau. Mocht er iets niet kloppen neem dan contact op met het Goudse Hervormde kerkelijke bureau. Adres: Willem de Zwijgersingel 1, 2805 BP Gouda Telefoon:0182-513360 Email:kerkelijkbureau@hervormdgouda.nl';
  $page .= '</p>';
  $page .= '<dl class="admin-list">';

  $page .= '<dt>';
  $page .= '<a href="'.url(OOSTPOORT_FAMILY_LIST).'/A">Bekijk leden gegevens</a>';
  $page .= '</dt>';
  $page .= '<dd>';
  $page .= 'Extra informatie is nu nog niet beschikbaar';
  $page .= '</dd>';

  $page .= '<dt>';
  $page .= '<a href="'.url(OOSTPOORT_FAMILY_BLOCK).'">Huis bezoek plannen</a>';
  $page .= '</dt>';
  $page .= '<dd>';
  $page .= 'Extra informatie is nu nog niet beschikbaar';
  $page .= '</dd>';

  $page .= '<dt>';
  $page .= '<a href="'.url(OOSTPOORT_MEMBER_AGE).'">Bepaalde leeftijdscategorie tonen</a>';
  $page .= '</dt>';
  $page .= '<dd>';
  $page .= 'Extra informatie is nu nog niet beschikbaar';
  $page .= '</dd>';

  $page .= '<dt>';
  $page .= '<a href="'.url(OOSTPOORT_JUBILEA_BIRTHDAY).'">Verjaardagsjubilea van dit jaar</a>';
  $page .= '</dt>';
  $page .= '<dd>';
  $page .= 'Extra informatie is nu nog niet beschikbaar';
  $page .= '</dd>';

  $page .= '<dt>';
  $page .= '<a href="'.url(OOSTPOORT_JUBILEA_MARRIED).'">Huwelijksjubilea van dit jaar</a>';
  $page .= '</dt>';
  $page .= '<dd>';
  $page .= 'Extra informatie is nu nog niet beschikbaar';
  $page .= '</dd>';

  $page .= '<br/>';
  $page .= '<br/>';

  $page .= '<dt>';
  $page .= '<a href="'.url(OOSTPOORT_UPLOAD).'">Upload een nieuw ledenbestand</a>';
  $page .= '</dt>';
  $page .= '<dd>';
  $page .= 'Extra informatie is nu nog niet beschikbaar';
  $page .= '</dd>';

  $page .= '</dl>';
  $page .= '</div>';
  $page .= '</div>';

  print theme("page", $page);
}

// ##################################################################################
// JUBILEA OVERVIEW
// ##################################################################################

function oostpoort_jubilea_married()  
{
  global $user;

  // Breadcrumb menu
  $page  = '<div class="breadcrumb">';
  $page .= '<a href="'.url("").'">Home</a> > ';
  $page .= '<a href="'.url(OOSTPOORT_MENU).'">Menu</a> > ';
  $page .= 'Huwelijk jubilea ';
  $page .= '</div>';

  $page .= '<div class="oostpoort">';

  drupal_set_title(t('Oostpoort huwelijk jubilea' ) );

  $page .= '<br/>';

  $x=array(12, 25, 40, 45, 50, 55, 60, 65, 70);
  foreach ($x as $value)
  {
    $page .= 'Leden die '.$value.' jaar getrouwd zijn<br/>';
    $year = date("Y")-$value;
    $query   = 'select mid, voornamen, voegsel, achternaam, straatnaam, huisnummer, postcode, woonplaats, geboorte_datum, huwelijk_datum, kerklidnr from {oostpoort_members} WHERE YEAR(huwelijk_datum)='.$year.' GROUP BY straatnaam, huisnummer, huwelijk_datum having ( COUNT(huwelijk_datum)=2) order by huwelijk_datum';

//select achternaam, straatnaam, huisnummer, huwelijk_datum from oostpoort_members as willem WHERE YEAR(huwelijk_datum)=1975
//GROUP BY straatnaam, huisnummer, huwelijk_datum HAVING ( COUNT(straatnaam) = 2 )

    $queryResult = db_query($query);
    $page .= show_data($queryResult,2);
  }

  $page .= '</div>';
  print theme("page", $page);
}

function oostpoort_jubilea_birthday()  
{
  global $user;

  // Breadcrumb menu
  $page  = '<div class="breadcrumb">';
  $page .= '<a href="'.url("").'">Home</a> > ';
  $page .= '<a href="'.url(OOSTPOORT_MENU).'">Menu</a> > ';
  $page .= 'Verjaardag jubilea ';
  $page .= '</div>';

  $page .= '<div class="oostpoort">';

  drupal_set_title(t('Oostpoort verjaardag jubilea' ) );

  $page .= '<br/>';

  $x=array(50, 65, 70, 75, 80, 85, 90, 95);
  foreach ($x as $value)
  {
    $page .= 'Leden die '.$value.' jaar worden dit jaar<br/>';
    $year = date("Y")-$value;
    $query   = 'select mid, voornamen, voegsel, achternaam, straatnaam, huisnummer, postcode, woonplaats, geboorte_datum, kerklidnr 
      from {oostpoort_members} WHERE YEAR(geboorte_datum)='.$year.' order by geboorte_datum';
    $queryResult = db_query($query);
    $page .= show_data($queryResult,1);
  }

  // Query Database (100 jaar)
  $page .= 'Leden die 100 jaar en ouder worden dit jaar<br/>';
  $year = date("Y")-100;
  $query   = 'select mid, voornamen, voegsel, achternaam, straatnaam, huisnummer, postcode, woonplaats, geboorte_datum, kerklidnr 
from {oostpoort_members} WHERE (YEAR(geboorte_datum)<='.$year.' and YEAR(geboorte_datum)!=1900) order by geboorte_datum';
  $queryResult = db_query($query);
  $page .= show_data($queryResult,1);

  $page .= '</div>';
  print theme("page", $page);
}

function show_data($queryResult, $mode)
{
  $page .= '<table width=100% border=1 cellpadding=3 cellspacing=3>';

  // Show Banner
  $page .= '<tr><td>';
  if (user_access('access administration pages')) 
  {
     $page .= '<b>'.t('Kerk Lidnr.').'</b>';
     $page .= '</td><td>';
  }
  if ($mode==1)
  {
    $page .= '<b>'.t('Foto').'</b>';
    $page .= '</td><td>';
  }
  $page .= '<b>'.t('Naam').'</b>';
  $page .= '</td><td>';
  $page .= '<b>'.t('Straat').'</b>';
  $page .= '</td><td>';
  $page .= '<b>'.t('Plaats').'</b>';
  $page .= '</td><td>';
  $page .= '<b>'.t('Postcode').'</b>';
  $page .= '</td><td>';
  if ($mode==1)
  {
    $page .= '<b>'.t('Geboorte datum').'</b>';
    $page .= '</td><td>';
  }
  if ($mode==2)
  {
    $page .= '<b>'.t('Huwelijk datum').'</b>';
    $page .= '</td><td>';
  }
  $page .= '<b>'.t('Telefoon').'</b>';
  $page .= '</td></tr>';

  // Show all found members
  $page_tmp='';
  while ($data = db_fetch_object($queryResult))
  {
     $page_tmp .= '<tr><td width=50>';
     if (user_access('access administration pages')) 
     {
        $page_tmp .= $data->kerklidnr;
        $page_tmp .= '</td><td>';
     }

    $telephone=oostpoort_get_item2($data->kerklidnr,2);
    $image=oostpoort_get_item2($data->kerklidnr,8);

    if ($mode==1)
    {
      if (strlen($image)>0)
      {
        $page_tmp .= '<a href="'.url(OOSTPOORT_MEMBER_VIEW.'/'.$data->mid).'">';
        $filename=url(OOSTPOORT_THUMBNAILS_DIR.'/'.$image);
        $filename=str_replace(array("?q="), "", $filename);
        $page_tmp .= '<img src="'.$filename.'" width=25 height=30/></a>';
      }
      $page_tmp .= '</td><td>';
    }
    if ($mode==1)
    {
      $page_tmp .= l($data->voornamen.' '.$data->voegsel.' '.$data->achternaam, OOSTPOORT_MEMBER_VIEW.'/'.$data->mid);
    }
    else
    {
      $page_tmp .= 'Familie '.$data->voegsel.' '.$data->achternaam;
    }
    $page_tmp .= '</td><td>';
    $page_tmp .= $data->straatnaam.' '.$data->huisnummer;
    $page_tmp .= '</td><td>';
    $page_tmp .= $data->woonplaats;
    $page_tmp .= '</td><td>';
    $page_tmp .= $data->postcode;
    $page_tmp .= '</td><td>';
    if ($mode==1)
    {
      list($year, $month, $day) = split('[/.-]', $data->geboorte_datum);
      $page_tmp .= $day.'-'.$month.'-'.$year;
      $page_tmp .= '</td><td>';
    }
    if ($mode==2)
    {
      list($year, $month, $day) = split('[/.-]', $data->huwelijk_datum);
      $page_tmp .= $day.'-'.$month.'-'.$year;
      $page_tmp .= '</td><td>';
    }
    $page_tmp .= $telephone;
    $page_tmp .= '</td></tr>';
  }

  if ( $page_tmp!='') 
  {
     // Show Content
     $page .= $page_tmp;
  }
  else 
  {
    // No content found
    $page .= '<tr><td>';
    $page .= t('Geen informatie gevonden');
    $page .= '</td><td>';
    $page .= '</td><td>';
    $page .= '</td><td>';
    $page .= '</td><td>';
    $page .= '</td></tr>';
  }
  $page .= '</table>';

  return $page;
}

// ##################################################################################
// FAMILY LIST VIEW
// ##################################################################################

/*
 * Function shows all family in a list form
 * @return HTML
 */
function oostpoort_family_list( $sort='', $search='') {

  global $user;

  // Breadcrumb menu
  $page  = '<div class="breadcrumb">';
  $page .= '<a href="'.url("").'">Home</a> > ';
  $page .= '<a href="'.url(OOSTPOORT_MENU).'">Menu</a> > ';
  $page .= 'Family';
  $page .= '</div>';

  $page .= '<div class="oostpoort">';

  drupal_set_title(t('Oostpoort familie lijst'));

  // Get search value out post or session scope
  $search=$_POST['search'];

  // Set sort value in session scope
  $_SESSION["sort"]=$sort;

  $page .= '<br/>';
  $page .= '<table border=0 >';
  $page .= '<tr>';

  $page .= '<td >';
  $page .= '<form action="'.url(OOSTPOORT_FAMILY_LIST).'" method="POST">';
  $page .= '<input id="text" name="search" size="40" maxlength="40" type="text" value="'.$search.'" ';
  $page .= '<input type="submit" value="'.t('Zoeken').'" />';
  $page .= '</form>';
  $page .= '</td>';

  //$page .= '<table border=0 >';
  $page .= '<tr>';

  $page .= '<td ALIGN="left">';
  $sort_bar=array("A","B","C","D","E","F","G","H","I","J","K","L","M","N","O","P", "Q","R","S","T","U","V","W","X","Y","Z");
  if ($sort=='') $page .= '<B>';
  $page .= '<a href="'.url(OOSTPOORT_FAMILY_LIST).'">'.t('ALLES').'</a>|';
  if ($sort=='') $page .= '</B>';
  for ($i=0; $i<26; $i++)
  {
     if ($sort==$sort_bar[$i]) $page .= '<B>';
     $page .= '<a href="'.url(OOSTPOORT_FAMILY_LIST.'/'.$sort_bar[$i]).'">'.$sort_bar[$i].'</a>|';
     if ($sort==$sort_bar[$i]) $page .= '</B>';
  }
  $page .= '</td>';

  $page .= '</tr>';
  $page .= '</table>';

  // Query Database
  $query  = 'select distinct achternaam, straatnaam, huisnummer, postcode, woonplaats from {oostpoort_members} where ';
  if (strlen($search)==0)
  {
    $query  .= 'achternaam LIKE "'.$sort.'%" order by achternaam';
  }
  else
  { 
    $query  .= 'achternaam LIKE "'.$search.'%" order by achternaam';
  }
  $queryResult = db_query($query);

  $page .= '<table width=100% border="1" cellpadding="3" cellspacing="3">';

  // Show Banner
  $page .= '<td>';
  $page .= '<b>'.t('Naam').'</b>';
  $page .= '</td><td>';
  $page .= '<b>'.t('Straat').'</b>';
  $page .= '</td><td>';
  $page .= '<b>'.t('Postcode').'</b>';
  $page .= '</td><td>';
  $page .= '<b>'.t('Plaats').'</b>';
  $page .= '</td></tr>';

  // Show all found address
  $page_tmp='';
  while ($data = db_fetch_object($queryResult))
  {
    //$key=oostpoort_encode($data->postcode.$data->huisnummer);
    $key=$data->postcode.$data->huisnummer;
    $page_tmp .= '<tr><td width=60>';
    $page_tmp .= l($data->achternaam, OOSTPOORT_FAMILY_VIEW."/".$key);
    $page_tmp .= '</td><td>';
    $page_tmp .= $data->straatnaam.' '.$data->huisnummer;
    $page_tmp .= '</td><td>';
    $page_tmp .= $data->postcode;
    $page_tmp .= '</td><td>';
    $page_tmp .= $data->woonplaats;
    $page_tmp .= '</td></tr>';
  }

  if ( $page_tmp!='') {
     // Show Content
     $page .= $page_tmp;
  }
  else 
  {
    // No content found
    $page .= '<tr><td>';
    $page .= t('Geen informatie gevonden');
    $page .= '</td><td>';
    $page .= '</td><td>';
    $page .= '</td><td>';
    $page .= '</td></tr>';
  }
  $page .= '</table>';

  print theme("page", $page);
}

// ##################################################################################
// FAMILY MEMBER VIEW
// ##################################################################################

/**
 * Render a page showing the selected family in detail
 * @return HTML
 */
function oostpoort_family_view( $parameters)  
{
  global $user;

  // Breadcrumb menu
  $page  = '<div class="breadcrumb">';
  $page .= '<a href="'.url("").'">Home</a> > ';
  $page .= '<a href="'.url(OOSTPOORT_MENU).'">Menu</a> > ';
  $page .= '<a href="'.url(OOSTPOORT_FAMILY_LIST).'/'.$_SESSION["sort"].'">Family</a> > ';
  $page .= 'View';
  $page .= '</div>';

  $page .= '<div class="oostpoort">';

  // Set sort value in session scope
  $_SESSION["parameters"]=$parameters;

  drupal_set_title(t('Oostpoort familie overzicht') );

  // Debugging value
  $border=0;

  //$parameters=oostpoort_decode($parameters);
  //if ($parameters==false) 
  //{ 
  //   print theme("page", $page);
  //   return "";
  // }

  $zipcode=substr($parameters,0,7);
  $nr=substr($parameters,7);

  $query  = 'SELECT mid, geslacht, aanschrijf_naam, achternaam, geboorte_datum, straatnaam, huisnummer, postcode, ';
  $query .= 'woonplaats, kerklidnr FROM {oostpoort_members} WHERE postcode="'.$zipcode.'" AND huisnummer="'.$nr.'" order by geboorte_datum';
  $queryResult = db_query($query);
  $data = db_fetch_object($queryResult);

  $telephone=oostpoort_get_item2($data->kerklidnr,2);
  $street=$data->straatnaam.' '.$data->huisnummer;
  $city=$data->woonplaats;

  // Show address information in readonly mode
  $page .= '<br/>';

  $page .= '<table width="100%" cellpadding="1" >';

  $page .= '<tr><td valign="top">';
  $page .= '<b>'.$data->achternaam.'</b><br/>';
  $page .= $street.'<br/>';
  $page .= $data->postcode.'&nbsp;&nbsp;'.$data->street.'&nbsp;&nbsp;'.$city.'<br/>';
  $page .= 'Nederland<br/>';
  $page .= $telephone.'<br/>';
  $page .= '</td>';

  $page .= '</tr>';
  $page .= '</table>';

  $page .= '<table width=100% cellpadding=1>';

  // Show Banner
  $page .= '<tr><td>';
  if (user_access('access administration pages')) 
  {
    $page .= '<b>'.t('Id').'</b>';
    $page .= '</td><td>';
  }
  $page .= '<b>'.t('Foto').'</b>';
  $page .= '</td><td>';
  $page .= '<b>'.t('Geslacht').'</b>';
  $page .= '</td><td>';
  $page .= '<b>'.t('Naam').'</b>';
  $page .= '</td><td>';
  $page .= '<b>'.t('Geboren').'</b>';
  $page .= '</td><td>';
  $page .= '<b>'.t('Mobiel').'</b>';
  $page .= '</td><td>';
  $page .= '<b>'.t('Email').'</b>';
  $page .= '</td></tr>';

  // Show all found members
  do
  {
    $email=oostpoort_get_item2($data->kerklidnr,1);
    $mobile=oostpoort_get_item2($data->kerklidnr,3);
    $image=oostpoort_get_item2($data->kerklidnr,8);

    $page .= '<tr><td>';
    if (user_access('access administration pages')) 
    {
       $page .= $data->kerklidnr;
       $page .= '</td><td>';
    }
    if (strlen($image)>0)
    {
      $page .= '<a href="'.url(OOSTPOORT_MEMBER_VIEW.'/'.$data->mid).'">';
      $filename=url(OOSTPOORT_THUMBNAILS_DIR.'/'.$image);
      $filename=str_replace(array("?q="), "", $filename);
      $page .= '<img src="'.$filename.'" width=25 height=30/></a>';
    }
    $page .= '</td><td>';
    $page .= $data->geslacht;
    $page .= '</td><td>';
    $page .= l($data->aanschrijf_naam,OOSTPOORT_MEMBER_VIEW.'/'.$data->mid);
    $page .= '</td><td>';
    list($year, $month, $day) = split('[/.-]', $data->geboorte_datum);
    $page .= $day.'-'.$month.'-'.$year;
    $page .= '</td><td>';
    $page .= $mobile;
    $page .= '</td><td>';
    $page .= l($email,'mailto:'.$email);
    $page .= '</td></tr>';
  }
  while ($data = db_fetch_object($queryResult));

  $page .= '</table>';
  $page .= '<br/>';

  // Navigation Bar
  $page .= '<table border="0" >';
  $page .= '<tr>';

  $page .= '<td align="left">';
  $page .= '<form action="'.url(OOSTPOORT_FAMILY_LIST.'/'.$_SESSION["sort"]).'" method="POST">';
  $page .= '<input type="submit" value="'.t('Terug').'" />';
  $page .= '</form>';
  $page .= '</td>';

  $page .= '<td align="left">';
  $page .= '<form action="'.url(OOSTPOORT_FAMILY_MAP).'" method="POST">';
  $page .= '<input type="hidden" name="street" value="'.$street.'" />';
  $page .= '<input type="hidden" name="city" value="'.$city.'" />';
  $page .= '<input type="hidden" name="country" value="Nederland" />';
  $page .= '<input type="submit" value="'.t('Kaart').'" />';
  $page .= '</form>';
  $page .= '</td>';

  $page .= '</tr>';
  $page .= '</table>';

  $page .= '</div>';
  print theme("page", $page);
}

// ##################################################################################
// FAMILY MAP VIEW
// ##################################################################################

function oostpoort_family_map() 
{
  $parameters=$_SESSION["parameters"];

  // Breadcrumb menu
  $page  = '<div class="breadcrumb">';
  $page .= '<a href="'.url("").'">Home</a> > ';
  $page .= '<a href="'.url(OOSTPOORT_MENU).'">Menu</a> > ';
  $page .= '<a href="'.url(OOSTPOORT_FAMILY_LIST).'/'.$_SESSION["sort"].'">Family</a> > ';
  $page .= '<a href="'.url(OOSTPOORT_FAMILY_VIEW.'/'.$parameters).'">View</a> > ';
  $page .= 'Map';
  $page .= '</div>';

  $page .= '<div class="oostpoort">';

  drupal_set_title(t('Familie kaart'));

  // Fetch search parameter out HTTP request
  $street=$_POST['street'];
  $city=$_POST['city'];
  $country=$_POST['country'];

  drupal_set_html_head('<meta http-equiv="content-type" content="text/html; charset=UTF-8" />');
  drupal_set_html_head('<script type="text/javascript" language="javascript" src="http://api.maptp.map24.com/ajax?appkey='.variable_get('addressbook_map_key','').'"></script>');
  drupal_set_html_head('<script type="text/javascript">');

  drupal_set_html_head('function goMap24()');
  drupal_set_html_head('{');
  drupal_set_html_head('  Map24.loadApi( ["core_api", "wrapper_api"] , map24ApiLoaded );;');
  drupal_set_html_head('}');

  drupal_set_html_head('function map24ApiLoaded()');
  drupal_set_html_head('{');
  drupal_set_html_head('  Map24.MapApplication.init( { NodeName: "maparea" } );');
  drupal_set_html_head('}');

  drupal_set_html_head('function geocode( searchText )');
  drupal_set_html_head('{');
  drupal_set_html_head('  var geocoder = new Map24.GeocoderServiceStub();');
  drupal_set_html_head('  geocoder.geocode( searchText );');
  drupal_set_html_head('}');

  drupal_set_html_head('</script>');

  $page.='<body onload="goMap24()">';

   // Show menu Bar
  $page .= '<br/>';
  $page .= '<table width="100%" border=0>';
  $page .= '<tr>';

  $page .= '<td valign="left">';
  $page .= '<b>'.t('Adres: ').$street.', '.$city.', '.$country.'</b>';
  $page .= '</td>';

  $page .= '<td  valign="right">';
  $page.=' <input type="submit" value="'.t('Zoeken').'" onclick="return geocode(\''.$street.','.$city.','.$country.'\')">';
  $page .= '</td>';

  $page .= '<td valign="right">';
  $page .= '<form action="'.url(OOSTPOORT_FAMILY_VIEW.'/'.$parameters).'" method="POST">';
  $page .= '<input type="submit" name="commit" value="'.t('Return').'" />';
  $page .= '</form>';
  $page .= '</td>';

  $page .= '</tr>';
  $page .= '</table>';

  $page .= '<br/>';
  $page .= '<div id="maparea" style="width:700px;height:500px;background-color:#E0E0E0;"></div>';
  $page .= '</body>';

  $page .= '</div>';
  print theme("page", $page);
}

// ##################################################################################
// FAMILY LIST BLOCK
// ##################################################################################

/**
 * Render a page showing the selected address for editing
 * @return HTML
 */
function oostpoort_family_block()  
{
  global $user;

  $block=$_POST['block'];
  if (strlen($block)==0) $block="blok 1";

  // Breadcrumb menu
  $page  = '<div class="breadcrumb">';
  $page .= '<a href="'.url("").'">Home</a> > ';
  $page .= '<a href="'.url(OOSTPOORT_MENU).'">Menu</a> > ';
  $page .= 'Family > Block';
  $page .= '</div>';

  $page .= '<div class="oostpoort">';

  drupal_set_title(t('Oostpoort familielijst gefilterd op blok' ) );

  $page .= '<br/>';

  $page .= '<form action="'.url(OOSTPOORT_FAMILY_BLOCK).'" method="POST">';
  $page .= '<select name="block">';
  $query = 'select distinct sectie from {oostpoort_members} order by sectie';
  $queryResult = db_query($query);
  while ($data = db_fetch_object($queryResult))
  {
     $page.='<option value="'.$data->sectie.'" ';
     if ($block==$data->sectie) $page.='selected="selected" ';
     $page.='>'.$data->sectie.'</option>';

     //$page.='<option value="'.$data->sectie.'">'.$data->sectie.'</option>';
  }
  $page .='</select> '; 
  $page .= '<input type="submit" value="'.t('Zoeken').'" />';
  $page .= '</form>';

  // Query Database
  $query   = 'select distinct achternaam, straatnaam, huisnummer, postcode, woonplaats from {oostpoort_members} ';
  $query  .= 'where sectie LIKE "'.$block.'"';
  $queryResult = db_query($query);

  $page .= '<table width=100% border="1" cellpadding="3" cellspacing="3">';

  // Show Banner
  $page .= '<td>';
  $page .= '<b>'.t('Naam').'</b>';
  $page .= '</td><td>';
  $page .= '<b>'.t('Straat').'</b>';
  $page .= '</td><td>';
  $page .= '<b>'.t('Postcode').'</b>';
  $page .= '</td><td>';
  $page .= '<b>'.t('Plaats').'</b>';
  $page .= '</td><td>';
  $page .= '<b>'.t('Laatste bezoekdatum').'</b>';
  $page .= '</td></tr>';

  // Show all found address
  $page_tmp='';
  while ($data = db_fetch_object($queryResult))
  {
    //$key=oostpoort_encode($data->postcode.$data->huisnummer);
    $key=$data->postcode.$data->huisnummer;
    $page_tmp .= '<tr><td width=60>';
    $page_tmp .= l($data->achternaam, OOSTPOORT_FAMILY_VIEW."/".$key);
    $page_tmp .= '</td><td>';
    $page_tmp .= $data->straatnaam.' '.$data->huisnummer;
    $page_tmp .= '</td><td>';
    $page_tmp .= $data->postcode;
    $page_tmp .= '</td><td>';
    $page_tmp .= $data->woonplaats;
    $page_tmp .= '</td></td>';
    $page_tmp .= '</td></tr>';
  }

  if ( $page_tmp!='') {
     // Show Content
     $page .= $page_tmp;
  }
  else 
  {
    // No content found
    $page .= '<tr><td>';
    $page .= t('Geen informatie gevonden');
    $page .= '</td><td>';
    $page .= '</td><td>';
    $page .= '</td><td>';
    $page .= '</td></tr>';
  }
  $page .= '</table>';

  $page .= '</div>';
  print theme("page", $page);
}


// ##################################################################################
// MEMBER LIST AGE
// ##################################################################################

/**
 * Render a page showing the selected address for editing
 * @return HTML
 */
function oostpoort_member_age()  
{
  global $user;

  $age=$_POST['age'];
  if (strlen($age)==0) $age=0;

  // Breadcrumb menu
  $page  = '<div class="breadcrumb">';
  $page .= '<a href="'.url("").'">Home</a> > ';
  $page .= '<a href="'.url(OOSTPOORT_MENU).'">Menu</a> > ';
  $page .= 'Members > Age';
  $page .= '</div>';

  $page .= '<div class="oostpoort">';

  drupal_set_title(t('Oostpoort ledenlijst gefilterd op leeftijd' ) );

  $page .= '<br/>';

  $page .= '<form action="'.url(OOSTPOORT_MEMBER_AGE).'" method="POST">';
  $page .= 'Leeftijd is <input id="text" name="age" size="3" maxlength="3" type="text" value="'.$age.'"> jaar ';
  $page .= '<input type="submit" value="'.t('Zoeken').'" />';
  $page .= '</form>';

  // Query Database
  $query   = 'select mid, voornamen, voegsel, achternaam, straatnaam, huisnummer, postcode, woonplaats, geboorte_datum, kerklidnr  from {oostpoort_members} where leeftijd='.$age.' ';
  $query  .= 'order by achternaam';
  $queryResult = db_query($query);

  $page .= '<table width=100% border=1 cellpadding=3 cellspacing=3>';

  // Show Banner
  $page .= '<tr><td>';
  if (user_access('access administration pages')) 
  {
     $page .= '<b>'.t('Id').'</b>';
     $page .= '</td><td>';
  }
  $page .= '<b>'.t('Foto').'</b>';
  $page .= '</td><td>';
  $page .= '<b>'.t('Naam').'</b>';
  $page .= '</td><td>';
  $page .= '<b>'.t('Straat').'</b>';
  $page .= '</td><td>';
  $page .= '<b>'.t('Plaats').'</b>';
  $page .= '</td><td>';
  $page .= '<b>'.t('Postcode').'</b>';
  $page .= '</td><td>';
  $page .= '<b>'.t('Geboorte datum').'</b>';
  $page .= '</td><td>';
  $page .= '<b>'.t('Telefoon').'</b>';
  $page .= '</td><td>';
  $page .= '<b>'.t('Email').'</b>';
  $page .= '</td></tr>';

  // Show all found members
  $page_tmp='';
  while ($data = db_fetch_object($queryResult))
  {
     $page_tmp .= '<tr><td width=50>';
     if (user_access('access administration pages')) 
     {
        $page_tmp .= $data->kerklidnr;
        $page_tmp .= '</td><td>';
     }

    $email=oostpoort_get_item2($data->kerklidnr,1);
    $telephone=oostpoort_get_item2($data->kerklidnr,2);
    $image=oostpoort_get_item2($data->kerklidnr,8);

    if (strlen($image)>0)
    {
      $page_tmp .= '<a href="'.url(OOSTPOORT_MEMBER_VIEW.'/'.$data->mid).'">';
      $filename=url(OOSTPOORT_THUMBNAILS_DIR.'/'.$image);
      $filename=str_replace(array("?q="), "", $filename);
      $page_tmp .= '<img src="'.$filename.'" width=25 height=30/></a>';
    }
    $page_tmp .= '</td><td>';
    $page_tmp .= l($data->voornamen.' '.$data->voegsel.' '.$data->achternaam, OOSTPOORT_MEMBER_VIEW.'/'.$data->mid);
    $page_tmp .= '</td><td>';
    $page_tmp .= $data->straatnaam.' '.$data->huisnummer;
    $page_tmp .= '</td><td>';
    $page_tmp .= $data->woonplaats;
    $page_tmp .= '</td><td>';
    $page_tmp .= $data->postcode;
    $page_tmp .= '</td><td>';
    list($year, $month, $day) = split('[/.-]', $data->geboorte_datum);
    $page_tmp .= $day.'-'.$month.'-'.$year;
    $page_tmp .= '</td><td>';
    $page_tmp .= $telephone;
    $page_tmp .= '</td><td>';
    $page_tmp .= l($email,'mailto:'.$email);
    $page_tmp .= '</td></tr>';
  }

  if ( $page_tmp!='') 
  {
     // Show Content
     $page .= $page_tmp;
  }
  else 
  {
    // No content found
    $page .= '<tr><td>';
    $page .= t('Geen informatie gevonden');
    $page .= '</td><td>';
    $page .= '</td><td>';
    $page .= '</td><td>';
    $page .= '</td><td>';
    $page .= '</td></tr>';
  }
  $page .= '</table>';

  $page .= '</div>';
  print theme("page", $page);
}

// ##################################################################################
// MEMBER VIEW
// ##################################################################################

/**
 * Render a page showing the selected member in readonly mode
 * @return HTML
 */
function oostpoort_member_view( $mid=0 )  {

  global $user;

  $parameters=$_SESSION["parameters"];

  // Breadcrumb menu
  $page  = '<div class="breadcrumb">';
  $page .= '<a href="'.url("").'">Home</a> > ';
  $page .= '<a href="'.url(OOSTPOORT_MENU).'">Menu</a> > ';
  $page .= '<a href="'.url(OOSTPOORT_FAMILY_LIST).'/'.$_SESSION["sort"].'">Family</a> > ';
  $page .= '<a href="'.url(OOSTPOORT_FAMILY_VIEW.'/'.$parameters).'">View</a> > ';
  $page .= 'Member';
  $page .= '</div>';

  $page .= '<div class="oostpoort">';

  // Get search value out session scope
  $parameters=$_SESSION["parameters"];

  // Fetch data from HTTP request
  $commit = isset($_POST['commit']) ? '1' : '0';

  if ($commit=='1') 
  {
    // Insert extra memeber information in database
    $email=$_POST['email'];
    $mobile=$_POST['mobile'];
    $telephone=$_POST['telephone'];
    $work=$_POST['work'];
    $notes=$_POST['notes'];

    /* Fetch all active and wanted roles from the HTTP request */
    $i=0;
    $active_first=1;
    $wanted_first=1;
    $tmp=split( ",", variable_get('addressbook_roles',''));
    while ($tmp[$i]!='') 
    {
      if ($_POST["active_$tmp[$i]"]=='on')
      {
         if ($active_first=='1') 
         {
            $active_roles=$tmp[$i];
            $active_first=0;
         }
         else $active_roles.=';'.$tmp[$i];
      }

      if ($_POST["wanted_$tmp[$i]"]=='on')
      {
         if ($wanted_first=='1') 
         {
            $wanted_roles=$tmp[$i];
            $wanted_first=0;
         }
         else $wanted_roles.=';'.$tmp[$i];
      }
      $i++;
    }

    oostpoort_set_item($mid,1,$email);
    oostpoort_set_item($mid,2,$telephone);
    oostpoort_set_item($mid,3,$mobile);
    oostpoort_set_item($mid,4,$work);
    oostpoort_set_item($mid,5,$notes);
    oostpoort_set_item($mid,6,$active_roles);
    oostpoort_set_item($mid,7,$wanted_roles);
  }
  else
  { 
    // Fetch extra memeber information out database
    $email        = oostpoort_get_item($mid,1);
    $telephone    = oostpoort_get_item($mid,2);
    $mobile       = oostpoort_get_item($mid,3);
    $work         = oostpoort_get_item($mid,4);
    $notes        = oostpoort_get_item($mid,5);
    $active_roles = oostpoort_get_item($mid,6);
    $wanted_roles = oostpoort_get_item($mid,7);
    $image        = oostpoort_get_item($mid,8);
  }

  // Show information on screen
  drupal_set_title(t('Oostpoort lid overzicht') );

  // Fetch member from database
  $query  = 'SELECT geslacht, aanschrijf_naam, voornamen, straatnaam, huisnummer, postcode, woonplaats, geboorte_datum,';
  $query .= 'geboorte_plaats, doop_datum, doop_plaats, burgelijkestaat, kerkelijkestaat, huwelijk_datum, huwelijk_plaats, ';
  $query .= 'belijdenis_datum, belijdenis_plaats, herkomst_datum, herkomst_plaats, herkomst_datum, herkomst_plaats, ';
  $query .= 'mutatie_datum, sectie, wijknaam, kerkelijk_relatie, voorkeur_wijk, kerkblad, kerklidnr, last_updated FROM {oostpoort_members} ';
  $query .= 'WHERE mid='.$mid;
  $queryResult = db_query($query);
  $data = db_fetch_object($queryResult);

  $page .= '<form action="'.url(OOSTPOORT_MEMBER_VIEW.'/').$mid.'" method="POST">';
  $page .= "<br/><b>Algemene gegevens:</b><br/>";
  $page .= '<table cellpadding=2 width=100% >';

  $page .= '<tr><td valign="top" width=15%>';
  $page .= t('Geslacht');
  $page .= '</td><td>';
  $page .= '<input id="text" name="doop_plaats" size="50" type="text" value="'.$data->geslacht.'" READONLY />';
  $page .= '</td>';

  if (strlen($image)>=0) 
  {
    $page .= '<td ROWSPAN=9 valign="top">';
    $page .= '<a href="'.url(OOSTPOORT_PICTURE_VIEW.'/').$mid.'">';
    $page.='<img align="right" src="'.url(OOSTPOORT_THUMBNAILS_DIR.'/'.$image).'"/>';
    $page .= '</a>';
    $page .= '</td>';
  }
  $page .= '</tr>';

  $page .= oostpoort_view_line(t('Aanschrijfnaam'),'<input id="text" name="aanschrijfnaam" size="50" type="text" value="'.$data->aanschrijf_naam.'" READONLY />');
  $page .= oostpoort_view_line(t('Voornamen'),'<input id="text" name="voornamen" size="50" type="text" value="'.$data->voornamen.'" READONLY />');
  $page .= oostpoort_view_line(t('Straat'),'<input id="text" name="straat" size="50" type="text" value="'.$data->straatnaam.' '.$data->huisnummer.'" READONLY />');

  $page .= oostpoort_view_line(t('postcode'),'<input id="text" name="postcode" size="8" type="text" value="'.$data->postcode.'" READONLY />');
  $page .= oostpoort_view_line(t('woonplaats'),'<input id="text" name="woonplaats" size="50" type="text" value="'.$data->woonplaats.'" READONLY />');
  $page .= oostpoort_view_line(t('land'),'<input id="text" name="land" size="50" type="text" value="Nederland" READONLY />');

  list($year, $month, $day) = split('[/.-]', $data->geboorte_datum);
  $page .= oostpoort_view_birthday($day,$month,$year,'1',"Geboorte datum");

  if ($data->kerklidnr!=0)
  { 
     $page .= oostpoort_view_line(t('Telefoon'),'<input id="text" name="telephone" size="16" type="text" value="'.$telephone.'" />');
     $page .= oostpoort_view_line(t('Mobiel'),'<input id="text" name="mobile" size="16" type="text" value="'.$mobile.'" />');
     $page .= oostpoort_view_line(t('Email'),'<input id="text" name="email" size="50" type="text" value="'.$email.'" />');
     $page .= oostpoort_view_line(t('Werk'),'<textarea id="work" cols=55 rows=4 name="work" >'.$work.'</textarea>');
     $page .= oostpoort_view_line(t('Overige'),'<textarea id="notes" cols=55 rows=4 name="notes" >'.$notes.'</textarea>');
     $page .= '</tr></table>';
     $page .= oostpoort_view_roles($active_roles,$wanted_roles, '0');
  }
  else
  {  
     $page .= oostpoort_view_line(t('Telefoon'),'<input id="text" name="telephone" size="16" type="text" value="'.$telephone.'" READONLY />');
     $page .= oostpoort_view_line(t('Mobiel'),'<input id="text" name="mobile" size="16" type="text" value="'.$mobile.'" READONLY />');
     $page .= oostpoort_view_line(t('Email'),'<input id="text" name="email" size="50" type="text" value="'.$email.'" READONLY />');
     $page .= oostpoort_view_line(t('Werk'),'<textarea id="work" cols=55 rows=4 name="work" READONLY >'.$work.'</textarea>');
     $page .= oostpoort_view_line(t('Overige'),'<textarea id="notes" cols=55 rows=4 name="notes" READONLY>'.$notes.'</textarea>');
     $page .= '</tr></table>';
     $page .= oostpoort_view_roles($active_roles,$wanted_roles, '1');
  }

  // Show this information only for user with "view all" rights.
  if ( user_access('view all') ) 
  {
   $page .= "<b>Kerkelijke administratie gegevens:</b><br/>";
   $page .= '<table cellpadding=2 width=50%>';

   $page .= oostpoort_view_line(t('Kerklidnr'),'<input id="text" name="mid" size="10" type="text" value="'.$data->kerklidnr.'" READONLY />');
   $page .= oostpoort_view_line(t('Mid'),'<input id="text" name="mid" size="10" type="text" value="'.$mid.'" READONLY />');
   $page .= oostpoort_view_line(t('Last updated'),'<input id="text" name="last_updated" size="22" type="text" value="'.$data->last_updated.'" READONLY />');

   $page .= oostpoort_view_line(t('Geboorte plaats'),'<input size="50" type="text" value="'.$data->geboorte_plaats.'" READONLY />');

   list($year, $month, $day) = split('[/.-]', $data->doop_datum);
   $page .= oostpoort_view_birthday($day,$month,$year,'1',"Doop datum");

   $page .= oostpoort_view_line(t('Doop plaats'),'<input name="doop_plaats" size="50" type="text" value="'.$data->doop_plaats.'" READONLY />');
   $page .= oostpoort_view_line(t('Burgelijke staat'),'<input name="burgelijkstaat" size="50" type="text" value="'.$data->burgelijkestaat.'" READONLY />');
   $page .= oostpoort_view_line(t('Kerkelijke staat'),'<input name="kerkelijkstaat" size="50" type="text" value="'.$data->kerkelijkestaat.'" READONLY />');

   list($year, $month, $day) = split('[/.-]', $data->huwelijk_datum);
   $page .= oostpoort_view_birthday($day,$month,$year,'1',"Huwelijk datum");

   $page .= '<tr><td valign="top" width=15%>';
   $page .= t('Kerkelijke gezindte');
   $page .= '</td><td>';
   $page .= '<input id="text" name="kerkelijke_gezindte" size="50" type="text" value="'.$data->huwelijk_plaats.'" READONLY />';
   $page .= '</td></tr>';

   $page .= '<tr><td valign="top" width=15%>';

   list($year, $month, $day) = split('[/.-]', $data->belijdenis_datum);
   $page .= oostpoort_view_birthday($day,$month,$year,'1',"Belijdenis datum");
 
   $page .= '<tr><td valign="top" width=15%>';
   $page .= t('Belijdenis plaats');
   $page .= '</td><td>';
   $page .= '<input id="text" name="belijdenis_plaats" size="50" type="text" value="'.$data->belijdenis_plaats.'" READONLY />';
   $page .= '</td></tr>';
 
   list($year, $month, $day) = split('[/.-]', $data->herkomst_datum);
   $page .= oostpoort_view_birthday($day,$month,$year,'1',"Herkomst datum");

   $page .= '<tr><td valign="top" width=15%>';
   $page .= t('Herkomst plaats');
   $page .= '</td><td>';
   $page .= '<input id="text" name="herkomst_plaats" size="50" type="text" value="'.$data->herkomst_plaats.'" READONLY />';
   $page .= '</td></tr>';

   $page .= '<tr><td valign="top" width=15%>';
   $page .= t('Wijknaam');
   $page .= '</td><td>';
   $page .= '<input id="text" name="wijknaam" size="50" type="text" value="'.$data->wijknaam.'" READONLY />';
   $page .= '</td></tr>';

   $page .= '<tr><td valign="top" width=15%>';
   $page .= t('Sectie');
   $page .= '</td><td>';
   $page .= '<input id="text" name="sectie" size="50" type="text" value="'.$data->sectie.'" READONLY />';
   $page .= '</td></tr>';

   list($year, $month, $day) = split('[/.-]', $data->mutatie_datum);
   $page .= oostpoort_view_birthday($day,$month,$year,'1',"Mutatie datum");

   $page .= '<tr><td valign="top" width=15%>';
   $page .= t('Kerkelijke relatie');
   $page .= '</td><td>';
   $page .= '<input id="text" name="kerkelijke_relatie" size="50" type="text" value="'.$data->kerkelijke_relatie.'" READONLY />';
   $page .= '</td></tr>';

   $page .= '<tr><td valign="top" width=15%>';
   $page .= t('Voorkeur Wijk');
   $page .= '</td><td>';
   $page .= '<input id="text" name="voorkeur_wijk" size="50" type="text" value="'.$data->voorkeur_wijk.'" READONLY />';
   $page .= '</td></tr>';

   $page .= '<tr><td valign="top" width=15%>';
   $page .= t('Kerkblad');
   $page .= '</td><td>';
   $page .= '<input id="text" name="kerkblad" size="50" type="text" value="'.$data->kerkblad.'" READONLY />';
   $page .= '</td></tr>';

   $page .= '</table>';
  }

  // Show menu Bar
  $page .= '<br/>';
  $page .= '<table align="left">';
  $page .= '<tr>';

  if ($data->kerklidnr!=0)
  { 
    $page .= '<td valign="top">';
    $page .= '<tr><td valign="top">';
    $page .= '<input type="hidden" name="mid" value="'.$mid.'" />';
    $page .= '<input type="submit" name="commit" value="'.t('Opslaan').'" />';
  }
  $page .= '</form>';
  $page .= '</td>';

  if (($data->kerklidnr!=0) && (strlen($image)==0))
  {
      $page .= '<td valign="top">';
      $page .= '<form action="'.url(OOSTPOORT_PICTURE_EDIT.'/').$mid.'" method="POST">';
      $page .= '<input type="hidden" name="fid" value="'.$fid.'" />';
      $page .= '<input type="submit" value="'.t('Pasfoto toevoegen').'" />';
      $page .= '</form>';
      $page .= '</td>';
  }

  $page .= '<td valign="top">';
  $page .= '<form action="'.url(OOSTPOORT_FAMILY_VIEW.'/').$parameters.'" method="POST">';
  $page .= '<input type="submit" name="commit" value="'.t('Terug').'" />';
  $page .= '</form>';
  $page .= '</td>';

  $page .= '</tr>';
  $page .= '</table>';

  $page .= '<br/>';
  $page .= '<br/>';

  $page .= '</div>';
  print theme("page", $page);
}

// ##################################################################################
// CSV FILE UPLOAD 
// ##################################################################################

/**
 * process csv upload file.
 * @return errors in HTML format
 */
function oostpoort_process_csv_upload() {

  global $user;

  // Breadcrumb menu
  $page  = '<div class="breadcrumb">';
  $page .= '<a href="'.url("").'">Home</a> > ';
  $page .= '<a href="'.url(OOSTPOORT_MENU).'">Menu</a> > ';
  $page .= 'Upload CSV';
  $page .= '</div>';

  $page .= '<div class="oostpoort">';
  $page .= '<br/>';

  $line_counter=0;
  $csv_file_error=0;

  $myFile = 'files/upload.csv';
  $fh = fopen($myFile, 'r');

  // First delete all old information
  $query='delete from oostpoort_members';
  $queryResult = db_query($query);

  // Header line, skip it!
  $theData = fgets($fh);
  $line_counter++;

  $theData = fgets($fh);
  $line_counter++;
  while ($theData!='')
  {
    // Split read line in elements
    $value=split( ';' ,$theData);

    // Insert Family
    if (!oostpoort_insert_member($value))
    {
       // Query failed
       $page.=t('Line ').'['.$line_counter.'] '.t('contains an error (Family insert failed)').'<br/>';
    }
    $line_counter++;
    $theData = fgets($fh);
  }
  fclose($fh);

  // Delete csv file
  unlink($myFile);

  $page .= '<br/>';
  $page .= t('CSV bestand verwerkt!').'<br/>';
  $page .= '<br/>';
  $page .= '<form action="'.url(OOSTPOORT_FAMILY_LIST.'/'.$_SESSION["sort"]).'" method="POST">';
  $page .= '<input type="submit" value="'.t('Terug').'" />';
  $page .= '</form>';

  $page .= '</div>';
  return $page;
}

/**
 * Render a page for the csv addressbook upload
 * @return HTML
 */
function oostpoort_upload_csv() {

  global $user;

  // Breadcrumb menu
  $page  = '<div class="breadcrumb">';
  $page .= '<a href="'.url("").'">Home</a> > ';
  $page .= '<a href="'.url(OOSTPOORT_MENU).'">Menu</a> > ';
  $page .= 'Upload CSV';
  $page .= '</div>';

  $page .= '<div class="addressbook">';

  drupal_set_title(t('Leden administratie csv upload') );

  //only administrators can access this module
  if (!user_access('access administration pages')) {
    return drupal_access_denied();;
  }

   // Fetch Image upload in a HTTP request
  if ($_FILES['uploadedfile']['name']!='') {
    if ( (!strstr($_FILES['uploadedfile']['name'],'.csv')) && (!strstr($_FILES['uploadedfile']['name'],'.CSV')) )
    {
      $page .= '<br/>';
      $page.=t('Only CSV format is supported').'<br/>';
      $page .= '<br/>';

      // Return to family view page
      $page .= '<form action="/" method="POST">';
      $page .= '<input type="submit" value="'.t('Annuleren').'" />';
      $page .= '</form>';

      $page .= '</div>';
      return $page;
    }
    else
    {
      if (move_uploaded_file($_FILES['uploadedfile']['tmp_name'],'files/upload.csv')) {
        watchdog('user', 'A csv file is uploaded to the oostpoort');
        $page .= oostpoort_process_csv_upload();
      }
      else 
      {
        $page .= '<br/>';
        $page .= t('Failed to save csv file, try again!').'<br/>';
        $page .= '<br/>';

        // Return to family view page
        $page .= '<form action="/" method="POST">';
        $page .= '<input type="submit" value="'.t('Annuleren').'" />'.'<br/>';
        $page .= '</form>';

        $page .= '</div>';
        return $page;
      }
    }
  }

  if ($_FILES['uploadedfile']['name']=='') 
  {
    $page .= '<form enctype="multipart/form-data" action="upload" method="POST">';
    $page .= '<br/>';
    $page .= '<input type="hidden" />';
    $page .= t('Choose a csv file to upload:').' <input name="uploadedfile" type="file" />';

    $page .= '<br/>';
    $page .= '<div id="mission">';
    $page .= t('Warning: Only csv formatted files are supported.');
    $page .= '<br/>';
    $page .= t('File size must not exceed').ini_get('upload_max_filesize').'B';
    $page .= '<br/></div>';
    $page .= '<br/>';

    // Show menu Bar
    $page .= '<table>';
    $page .= '<tr><td>';
    $page .= '<input type="hidden" name="fid" value="'.$fid.'" />';
    $page .= '<input type="submit" value="'.t('Bestand uploaden').'" />';
    $page .= '</form>';
    $page .= '</td><td>';

    // Return to family view page
    $page .= '<form action="'.url(OOSTPOORT_MENU).'" method="POST">';
    $page .= '<input type="submit" value="'.t('Terug').'" />';
    $page .= '</form>';

    $page .= '</td></tr>';
    $page .= '</table>';
  }

  $page .= '</div>';
  print theme("page", $page);
}

// ##################################################################################
// VIEW IMAGE
// ##################################################################################

/**
 * Render a page showing the picture full screen.
 * @return HTML
 */
function oostpoort_picture_view( $mid=0 ) 
{
  global $user;

  // Breadcrumb menu
  $page  = '<div class="breadcrumb">';
  $page .= '<a href="'.url("").'">Home</a> > ';
  $page .= '<a href="'.url(OOSTPOORT_MENU).'">Menu</a> > ';
  $page .= '<a href="'.url(OOSTPOORT_FAMILY_LIST).'/'.$_SESSION["sort"].'">Family</a> > ';
  $page .= '<a href="'.url(OOSTPOORT_FAMILY_VIEW.'/'.$parameters).'">View</a> > ';
  $page .= '<a href="'.url(OOSTPOORT_MEMBER_VIEW.'/'.$mid).'">Member</a> > ';
  $page .= 'View Picture';
  $page .= '</div>';

  $page .= '<div class="oostpoort">';

  drupal_set_title(t('Oostpoort foto bekijken') );

  $image = oostpoort_get_item($mid,8);

  $picture_delete = isset($_POST['picture_delete']) ? '1' : '0';
  $go_delete = isset($_POST['go_delete']) ? '1' : '0';

  // Delete selected picture from disk and database
  if (($picture_delete=='1') && ($go_delete=='1')) 
  {
     if (is_file(OOSTPOORT_IMAGE_DIR.'/'.$image))
     {
       unlink(OOSTPOORT_IMAGE_DIR.'/'.$image);
     }
     if (is_file(OOSTPOORT_THUMBNAILS_DIR.'/'.$image)) 
     {
       unlink(OOSTPOORT_THUMBNAILS_DIR.'/'.$image);
     }
     oostpoort_delete_item($mid,8);
     return oostpoort_member_view($mid);
  }

  // Delete are you sure form
  if (($picture_delete=='1') && ($go_delete=='0')) 
  {
    $page .= '<br/>';
    $page .= t('Weet u zeker dat u de pasfoto wilt verwijderen?');
    $page .= '<br/>';
    $page .= '<br/>';
    $page .= '<table align="left">';
    $page .= '<tr>';
    $page .= '<td>';
    $page .= '<form action="'.url(OOSTPOORT_PICTURE_VIEW.'/'.$mid).'" method="POST">';
    $page .= '<input type="submit" name="go_delete" value="'.t('Ja').'" />';
    $page .= '<input type="hidden" name="picture_delete" />';
    $page .= '</form>';
    $page .= '</td>';
    $page .= '<td>';
    $page .= '<form action="'.url(OOSTPOORT_MEMBER_VIEW.'/'.$mid).'" method="POST">';
    $page .= '<input type="submit" name="cancel_delete" value="'.t('Nee').'" />';
    $page .= '</form>';
    $page .= '</td></tr>';
    $page .= '</table>';
    $page .= '</div>';
    return $page;
  }
  else
  {
    // Show menu Bar
    $page .= '<br/>';
    $page .= '<table align="left">';
    $page .= '<tr>';

    $page .= '<td valign="top">';
    $page .= '<form action="'.url(OOSTPOORT_PICTURE_VIEW.'/'.$mid).'" method="POST">';
    $page .= '<input type="submit" name="picture_delete" value="'.t('Delete').'" />';
    $page .= '</form>';
    $page .= '</td>';

    $page .= '<td>';
    $page .= '<form action="'.url(OOSTPOORT_MEMBER_VIEW.'/'.$mid).'" method="POST">';
    $page .= '<input type="submit" name="cancel" value="'.t('Terug').'" />';
    $page .= '</form>';
    $page .= '</td>';

    $page .= '</tr>';
    $page .= '</table>';

    $page .= '<br/>';

    $filename=url(OOSTPOORT_IMAGE_DIR.'/'.$image);
    $page.='<img src="'.$filename.'"/>';
    $page .= '<br/>';
  }

  $page .= '</div>';
  print theme("page", $page);
}

// ##################################################################################
// EDIT IMAGE
// ##################################################################################

/**
 * Render a page for uploading a picture.
 * @return HTML
 */
function oostpoort_picture_edit( $mid=0 ) 
{
  global $user;

  // Breadcrumb menu
  $page  = '<div class="breadcrumb">';
  $page .= '<a href="'.url("").'">Home</a> > ';
  $page .= '<a href="'.url(OOSTPOORT_MENU).'">Menu</a> > ';
  $page .= '<a href="'.url(OOSTPOORT_FAMILY_LIST).'/'.$_SESSION["sort"].'">Family</a> > ';
  $page .= '<a href="'.url(OOSTPOORT_FAMILY_VIEW.'/'.$parameters).'">View</a> > ';
  $page .= '<a href="'.url(OOSTPOORT_MEMBER_VIEW.'/'.$mid).'">Member</a> > ';
  $page .= 'Add Picture';
  $page .= '</div>';

  $page .= '<div class="oostpoort">';

  drupal_set_title(t('Foto toevoegen') );

  // Fetch Image upload in a HTTP request
  if ($_FILES['uploadedfile']['name']!='') 
  {
    if ( (strstr($_FILES['uploadedfile']['name'],'.jpg')) || (strstr( $_FILES['uploadedfile']['name'],'.JPG')) )
    {
      $error='0';
      if(!is_dir(OOSTPOORT_IMAGE_DIR))
      {
        if( !mkdir(OOSTPOORT_IMAGE_DIR) )
        {
          $page .= '<br/>';
          $page .= t('Creating image directory failed!');
          $page .= '<br/>';
          $error='1';
        }
      }
      $filename= date('YmdHis', time()).'.jpg';

       // Check dimensions of image
      $dimensions = getimagesize($_FILES['uploadedfile']['tmp_name']);
      $width  = $dimensions[0];
      $height = $dimensions[1];
      $resize = 0;

      // Limit picture 
      if ($width>$height)
      {
         if ($width>0) $ratio = 800 / $width;
         if ($ratio < 1)
         {
            $width=800;
            $height=$height*$ratio;
            $resize = 1;
         }
      }
      else 
      {
         if ($width>0) $ratio = 600 / $width;
         if ($ratio < 1)
         {
            $width=600;
            $height=$height*$ratio;
            $resize = 1;
         }
      }

      $page .= '<br/>';

      // Resize uploaded picture
      if ( $resize == 1 )
      {
         if (!image_scale($_FILES['uploadedfile']['tmp_name'], file_create_path(OOSTPOORT_IMAGE_DIR.'/'.$filename), $width, $height)) {
              $page .= '<br>';
              $page .= t('Bestand is te groot! Verklein foto (bv 800x600 pixels) en probeer het opnieuw.');
              $error='1';
              $page .= '<br>';
         }
      }
      else
      {
        // Not resize needed, move file to storage place
        copy($_FILES['uploadedfile']['tmp_name'],OOSTPOORT_IMAGE_DIR.'/'.$filename);
      }

      if ($error==0)
      {
        // Create thumbnails directory store
        if(!is_dir(OOSTPOORT_THUMBNAILS_DIR))
        {
          if( !mkdir(OOSTPOORT_THUMBNAILS_DIR) )
          {
            $page .= '<br/>';
            $page .= t('Creating image directory failed!');
            $page .= '<br/>';
            $error='1';
          }
        }

        $page .= '<br/>';

        $resize = 0;

        // Limit picture size on screen
        if ($width>$height)
        {
         if ($width>0) $ratio  = 160 / $width;
         if ($ratio < 1)
         {
            $width=160;
            $height=$height*$ratio;
            $resize = 1;
         }
        }
        else
        {
         if ($width>0) $ratio  = 120 / $width;
         if ($ratio < 1)
         {
            $width=120;
            $height=$height*$ratio;
            $resize = 1;
         }
        }

        // Create thumbnail picture
        // Resize uploaded picture
        if ( $resize == 1 )
        {
          if (!image_scale(OOSTPOORT_IMAGE_DIR.'/'.$filename, file_create_path(OOSTPOORT_THUMBNAILS_DIR.'/'.$filename), $width, $height)) {
            $page .= '<br>';
            $page .= t('Bestand is te groot! Verklein foto (bijvoorbeeld naar 800x600 pixels) en probeer het opnieuw.');
            $error='1';
            $page .= '<br>';
          }
        }
        else
        {
          // Not resize needed, move file to storage place
          copy(OOSTPOORT_IMAGE_DIR.'/'.$filename, OOSTPOORT_THUMBNAILS_DIR.'/'.$filename);
        }

        if ($error=='0') 
        {
          oostpoort_set_item($mid,8,$filename);
          return oostpoort_member_view($mid);
        }
      }
    }
    else 
    {
      $page .= '<br/>';
      $page.=t('Only JPG image format is supported');
      $page .= '<br/>';
      $_FILES['uploadedfile']['name']='';
    }
  }

  if ($_FILES['uploadedfile']['name']=='') 
  {
    $page .= '<form enctype="multipart/form-data" action="'.url(OOSTPOORT_PICTURE_EDIT.'/').$mid.'" method="POST">';
    $page .= '<br/>';
    $page .= '<input type="hidden" />';
    $page .= t('Selecteer een pasfoto bestand:').' <input name="uploadedfile" type="file" />';

    $page .= '<br/>';
    $page .= '<br/>';
    $page .= '<div id="mission">';
    $page .= t('Waarschuwing: Alleen jpg foto formaat wordt ondersteund.');
    $page .= '<br/>';
    $page .= t('Pasfoto mag niet groter zijn dan ').ini_get('upload_max_filesize').'B';
    $page .= '<br/></div>';
    $page .= '<br/>';

    // Show menu Bar
    $page .= '<table>';
    $page .= '<tr><td>';
    $page .= '<input type="hidden" name="fid" value="'.$fid.'" />';
    $page .= '<input type="submit" value="'.t('Pasfoto uploaden').'" />';
    $page .= '</form>';
    $page .= '</td><td>';

    // Return to member view page
    $page .= '<form action="'.url(OOSTPOORT_MEMBER_VIEW.'/').$mid.'" method="POST">';
    $page .= '<input type="hidden" name="fid" value="'.$fid.'" />';
    $page .= '<input type="submit" value="'.t('Annuleren').'" />';
    $page .= '</form>';

    $page .= '</td></tr>';
    $page .= '</table>';
  }
  else
  {
    $page .= '<br/>';

    // Return to member view page
    $page .= '<form action="'.url(OOSTPOORT_PICTURE_EDIT.'/').$mid.'" method="POST">';
    $page .= '<input type="hidden" name="fid" value="'.$fid.'" />';
    $page .= '<input type="submit" value="'.t('Terug').'" />';
    $page .= '</form>';
  }

  $page .= '</div>';
  print theme("page", $page);
}


// ##################################################################################
// THE END
// ##################################################################################
