<?php

/* 
**  Church Administration (oostpoort) module for drupal 
**
**  Copyright (C) 2009-2010
**  =======================
**
**  Created by wplaat
**
**  For more information visit the following website.
**  Website : http://www.plaatsoft.nl 
**
**  Or send an email to the following address.
**  Email   : info@plaatsoft.nl
**
**  This program is free software; you can redistribute it and/or modify
**  it under the terms of the GNU General Public License as published by
**  the Free Software Foundation, version 2.
**
**  This program is distributed in the hope that it will be useful,
**  but WITHOUT ANY WARRANTY; without even the implied warranty of
**  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
**  GNU General Public License for more details.
**
**  You should have received a copy of the GNU General Public License
**  along with this program; if not, write to the Free Software
**  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
*/

// Oostpoort module URLs
define('OOSTPOORT_MENU',            'base');

define('OOSTPOORT_FAMILY_LIST',     'family/list');
define('OOSTPOORT_FAMILY_VIEW',     'family/view');
define('OOSTPOORT_FAMILY_MAP',      'family/map');
define('OOSTPOORT_FAMILY_BLOCK',    'family/block');

define('OOSTPOORT_JUBILEA_BIRTHDAY','jubilea/birthday');
define('OOSTPOORT_JUBILEA_MARRIED', 'jubilea/married');

define('OOSTPOORT_UPLOAD',          'member/upload');
define('OOSTPOORT_MEMBER_AGE',      'member/age');
define('OOSTPOORT_MEMBER_VIEW',     'member/view');

define('OOSTPOORT_PICTURE_VIEW',    'picture/view');
define('OOSTPOORT_PICTURE_EDIT',    'picture/edit');

define('OOSTPOORT_IMAGE_DIR',       'files/oostpoort');
define('OOSTPOORT_THUMBNAILS_DIR',  'files/oostpoort/thumbnails');

define('OOSTPOORT_VISIT',           'visit/list');
define('OOSTPOORT_VISIT_DETAIL',    'visit/detail');
define('OOSTPOORT_VISIT_ADMIN',     'visit/admin');


// ##################################################################################
// THE END
// ##################################################################################
