<?php

/** 
 *  Church Administration (oostpoort) module for drupal 
 *
 *  Copyright (C) 2009-2010
 *  =======================
 *
 *  Created by wplaat
 *
 *  For more information visit the following website.
 *  Website : http://www.plaatsoft.nl 
 *
 *  Or send an email to the following address.
 *  Email   : info@plaatsoft.nl
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, version 2.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 *
 */

// ##################################################################################
// Defines
// ##################################################################################

// Version banner
define('VERSION', 'versie 0.70');

// Oostpoort Files store
define('OOSTPOORT_IMAGE_DIR',       'files/oostpoort');
define('OOSTPOORT_THUMBNAILS_DIR',  'files/oostpoort/thumbnails');

// Oostpoort URLs
define('OOSTPOORT_MENU',            'oostpoort');

define('OOSTPOORT_FAMILY',     		'oostpoort/family');

define('OOSTPOORT_JUBILEA_BIRTHDAY','oostpoort/jubilea/birthday');
define('OOSTPOORT_JUBILEA_MARRIED', 'oostpoort/jubilea/married');
define('OOSTPOORT_MEMBER_AGE',      'oostpoort/member/age');

define('OOSTPOORT_VISIT',           'oostpoort/visit');
define('OOSTPOORT_VISIT_ADMIN',     'oostpoort/visit/admin');
define('OOSTPOORT_UPLOAD_CSV',      'oostpoort/upload/csv');

// ##################################################################################
// Load all php modules
// ##################################################################################

// PHP module files
module_load_include('inc', 'oostpoort', 'oostpoort_utils'); 
module_load_include('inc', 'oostpoort', 'oostpoort_mainmenu');
module_load_include('inc', 'oostpoort', 'oostpoort_family');
module_load_include('inc', 'oostpoort', 'oostpoort_jubilea_birthday');
module_load_include('inc', 'oostpoort', 'oostpoort_jubilea_married');
module_load_include('inc', 'oostpoort', 'oostpoort_member_age');
module_load_include('inc', 'oostpoort', 'oostpoort_visit');
module_load_include('inc', 'oostpoort', 'oostpoort_visit_admin');
module_load_include('inc', 'oostpoort', 'oostpoort_upload_csv');

// ADD Java Scripts files
drupal_add_js(drupal_get_path('module', 'oostpoort'). '/oostpoort.js');
drupal_add_js(drupal_get_path('module', 'oostpoort'). '/ui.datepicker.js');

drupal_add_js('
	$(function() {
		$("#datepicker").datepicker({
			changeMonth: true,
			changeYear: true,
			dateFormat: "dd-mm-yy",
			appendText: " (dd-mm-yyyy)",
			dayNamesMin: ["Zo", "Ma", "Di", "Wo", "Do", "Vr", "Za"],
			monthNames: ["Januari","February","Maart","April","Mei","Juni","Juli","Augustus","September","Oktober","November","December"]
		});
	});','inline');

// Add CSS files
drupal_add_css(drupal_get_path('module', 'oostpoort') .'/oostpoort.css');
drupal_add_css(drupal_get_path('module', 'oostpoort') .'/datepicker.css');

// ##################################################################################
// Drupal hooks
// ##################################################################################

/**
 * help hook()
 * @return help texts
 */
function oostpoort_help($path, $arg) {

  $output = '';
  switch ($path) {
    case 'admin/modules#description':
      $output .= t('Oostpoort leden administratie module');
      break;
  }
  return $output;
}

/**
  * Valid permisions for this module
  * @return array an array of valid permission for the module
  */
function oostpoort_perm() 
{
  return array('view member','edit member');
}

/**
 * menu hook()
 * @return array of menu items
 */
function oostpoort_menu() {

  $items[OOSTPOORT_MENU] = array(
                   'title' => t('Oostpoort Menu'),
                   'page callback' => 'oostpoort_mainmenu',
                   'access arguments' => array('view member'),
                   'type' => MENU_CALLBACK);

  $items[OOSTPOORT_FAMILY] = array(
                   'title' => t('Oostpoort familie lijst'),
                   'page callback' => 'oostpoort_family',
                   'access arguments' => array('view member'),
                   'type' => MENU_CALLBACK);

  $items[OOSTPOORT_MEMBER_AGE] = array(
                   'title' => t('Oostpoort ledenlijst leeftijd'),
                   'page callback' => 'oostpoort_member_age',
                   'access arguments' => array('view member'),
                   'type' => MENU_CALLBACK);

  $items[OOSTPOORT_JUBILEA_BIRTHDAY] = array(
                   'title' => t('Oostpoort jubilea verjaarday'),
                   'page callback' => 'oostpoort_jubilea_birthday',
                   'access arguments' => array('view member'),
                   'type' => MENU_CALLBACK);

  $items[OOSTPOORT_JUBILEA_MARRIED] = array(
                   'title' => t('Oostpoort jubilea huwelijk'),
                   'page callback' => 'oostpoort_jubilea_married',
                   'access arguments' => array('view member'),
                   'type' => MENU_CALLBACK);
						
  $items[OOSTPOORT_VISIT] = array(
                   'title' => t('Oostpoort bezoekwerk'),
                   'page callback' => 'oostpoort_visit',
                   'access arguments' => array('view member'),
                   'type' => MENU_CALLBACK);

  $items[OOSTPOORT_UPLOAD_CSV] = array(
                   'title' => t('Oostpoort CSV upload'),
                   'page callback' => 'oostpoort_upload_csv',
                   'access arguments' => array('edit member'),
                   'type' => MENU_CALLBACK);
						 
  $items[OOSTPOORT_VISIT_ADMIN] = array(
                   'title' => t('Oostpoort bezoekwerk administratie'), 
                   'page callback' => 'oostpoort_visit_admin',
                   'access arguments' => array('edit member'),
                   'type' => MENU_CALLBACK);

  $items['admin/settings/oostpoort'] = array(
                   'title' => 'Oostpoort',
                   'description' => t('Leden administratie instellingen.'),
                   'page callback' => 'drupal_get_form',
                   'page arguments' => array('oostpoort_settings'),
                   'access arguments' => array('administer site configuration'),
                   'type' => MENU_NORMAL_ITEM);

  return $items;
}


/**
 * Module configuration settings
 * @return settings HTML or deny access
 */
function oostpoort_settings() {

 //only administrators can access this module
 if (!user_access('access administration pages')) 
 {
    return drupal_access_denied();
 }

  $form['general'] = array('#type' => 'fieldset', '#title' => t('General settings'));

  $form['general']['oostpoort_date'] = array(
     '#type' => 'textfield',
     '#title' => t('Date'),
     '#default_value' => variable_get('oostpoort_date', ''),
     '#description' => t("Enter the date (dd-mm-yyyy) when the latest csv file was uploaded."),
     '#maxlength' => '20',
     '#size' => '20');
     
  $form['map'] = array('#type' => 'fieldset', '#title' => t('Map settings'));

  $form['map']['oostpoort_map_link'] = array(
     '#type' => 'select',
     '#title' => t('Activate map'),
     '#default_value' => variable_get('oostpoort_map_link',0),
     '#options' => array( 0 => t('No'), 1 => t('Yes') ),
     '#description' => t('Enable / Disable Activate Google map.'));

  $form['map']['oostpoort_map_key'] = array(
     '#type' => 'textfield',
     '#title' => t('Google code access key'),
     '#default_value' => variable_get('oostpoort_map_key', ''),
     '#description' => t("Enter google code access key"),
     '#maxlength' => '50',
     '#size' => '50');
         
  $form['birthday'] = array('#type' => 'fieldset', '#title' => t('Birthday notification settings'));

  $form['birthday']['oostpoort_birthday_notification'] = array(
     '#type' => 'select',
     '#title' => t('Birthday email notification'),
     '#default_value' => variable_get('oostpoort_birthday_notification',0),
     '#options' => array( 0 => t('No'), 1 => t('Yes') ),
     '#description' => t('Enable / disable email birthday notification.'));

  $form['birthday']['oostpoort_birthday_subject'] = array(
     '#type' => 'textfield',
     '#title' => t('Subject of birtday e-mail'),
     '#default_value' => variable_get('oostpoort_birthday_subject','Happy birthday %username from %site_name'),
     '#maxlength' => 180,
     '#description' => t('Customize the subject of your birthday e-mail, which is sent to members upon their birthday.') .' '. t('Available variables are:') .' %username, %site_name');

  $form['birthday']['oostpoort_birthday_body'] = array(
     '#type' => 'textarea',
     '#title' => t('Body of birthday e-mail'),
     '#default_value' => variable_get('oostpoort_birthday_body',"Dear %username,\r\n\r\nCongratulation with your %user_age ste birthday.\r\nHave a nice day!\r\n"),
     '#rows' => 15,
     '#description' => t('Customize the body of the birthday e-mail, which is sent to members upon their birthday.') .' '. t('Available variables are:') .' %username, %user_age, %site_name');

  return system_settings_form($form);
}

// ##################################################################################
// THE END
// ##################################################################################
