<?php

/* 
**  Church Administration (oostpoort) module for drupal 
**
**  Copyright (C) 2009-2010
**  =======================
**
**  Created by wplaat
**
**  For more information visit the following website.
**  Website : http://www.plaatsoft.nl 
**
**  Or send an email to the following address.
**  Email   : info@plaatsoft.nl
**
**  This program is free software; you can redistribute it and/or modify
**  it under the terms of the GNU General Public License as published by
**  the Free Software Foundation, version 2.
**
**  This program is distributed in the hope that it will be useful,
**  but WITHOUT ANY WARRANTY; without even the implied warranty of
**  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
**  GNU General Public License for more details.
**
**  You should have received a copy of the GNU General Public License
**  along with this program; if not, write to the Free Software
**  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
*/

// General
include("oostpoort_general.inc");
include("oostpoort_utils.inc"); 
include("oostpoort_database.inc"); 

// Module Pages
include("oostpoort_mainmenu.inc");
include("oostpoort_jubilea_birthday.inc");
include("oostpoort_jubilea_married.inc");
include("oostpoort_family_list.inc");
include("oostpoort_family_members.inc");
include("oostpoort_family_map.inc");
include("oostpoort_visit.inc");
include("oostpoort_member_age.inc");
include("oostpoort_member_view.inc");
include("oostpoort_upload.inc");
include("oostpoort_picture_view.inc");
include("oostpoort_picture_edit.inc");

/**
 * help hook()
 * @return help texts
 */
function oostpoort_help($section) {

  $output = '';
  switch ($section) {
    case 'admin/modules#description':
      $output .= t('Oostpoort leden administratie module');
      break;
  }
  return $output;
}


/**
  * Valid permisions for this module
  * @return array an array of valid permission for the module
  */
function oostpoort_perm() 
{
  return array('view address','edit address', 'view all');
}


/**
 * menu hook()
 * @return array of menu items
 */
function oostpoort_menu() {

  $items = array();

  $items[] = array('path' =>  OOSTPOORT_MENU,
                   'title' => t('Oostpoort Menu'),
                   'callback' => 'oostpoort_mainmenu',
                   'access' => user_access('view address'),
                   'type' => MENU_CALLBACK);

  $items[] = array('path' =>  OOSTPOORT_UPLOAD,
                   'title' => t('Oostpoort CSV upload'),
                   'callback' => 'oostpoort_upload_csv',
                   'access' => user_access('add address'),
                   'type' => MENU_CALLBACK);

  $items[] = array('path' =>  OOSTPOORT_FAMILY_LIST,
                   'title' => t('Oostpoort familie lijst'),
                   'callback' => 'oostpoort_family_list',
                   'access' => user_access('view address'),
                   'type' => MENU_CALLBACK);

  $items[] = array('path' =>  OOSTPOORT_FAMILY_VIEW,
                   'title' => t('Oostpoort familie details'),
                   'callback' => 'oostpoort_family_view',
                   'access' => user_access('view address'),
                   'type' => MENU_CALLBACK);

  $items[] = array('path' => OOSTPOORT_FAMILY_MAP,
                   'title' => t('Oostpoort kaart bekijken'),
                   'callback' => 'oostpoort_family_map',
                   'access' => user_access('view address'),
                   'type' => MENU_CALLBACK);

  $items[] = array('path' =>  OOSTPOORT_MEMBER_AGE,
                   'title' => t('Oostpoort ledenlijst leeftijd'),
                   'callback' => 'oostpoort_member_age',
                   'access' => user_access('view address'),
                   'type' => MENU_CALLBACK);

  $items[] = array('path' =>  OOSTPOORT_FAMILY_BLOCK,
                   'title' => t('Oostpoort familie blok'),
                   'callback' => 'oostpoort_family_block',
                   'access' => user_access('view address'),
                   'type' => MENU_CALLBACK);

  $items[] = array('path' =>  OOSTPOORT_MEMBER_VIEW,
                   'title' => t('Oostpoort lid details'),
                   'callback' => 'oostpoort_member_view',
                   'access' => user_access('view address'),
                   'type' => MENU_CALLBACK);

  $items[] = array('path' =>  OOSTPOORT_JUBILEA_BIRTHDAY,
                   'title' => t('Oostpoort jubilea verjaarday'),
                   'callback' => 'oostpoort_jubilea_birthday',
                   'access' => user_access('view address'),
                   'type' => MENU_CALLBACK);

  $items[] = array('path' =>  OOSTPOORT_JUBILEA_MARRIED,
                   'title' => t('Oostpoort jubilea huwelijk'),
                   'callback' => 'oostpoort_jubilea_married',
                   'access' => user_access('view address'),
                   'type' => MENU_CALLBACK);

  $items[] = array('path' => OOSTPOORT_PICTURE_VIEW,
                   'title' => t('Oostpoort foto bekijken'),
                   'callback' => 'oostpoort_picture_view',
                   'access' => user_access('view address'),
                   'type' => MENU_CALLBACK);

  $items[] = array('path' => OOSTPOORT_PICTURE_EDIT,
                   'title' => t('Oostpoort foto uploaden'),
                   'callback' => 'oostpoort_picture_edit',
                   'access' => user_access('add address'),
                   'type' => MENU_CALLBACK);

  $items[] = array('path' => 'admin/settings/oostpoort',
                   'title' => t('Oostpoort'),
                   'description' => t('Instellingen Oostpoort leden administratie module.'),
                   'callback' => 'drupal_get_form',
                   'callback arguments' => array('oostpoort_settings'),
                   'access' => user_access('administer site configuration'),
                   'type' => MENU_NORMAL_ITEM);

  return $items;
}


/**
 * Module configuration settings
 * @return settings HTML or deny access
 */
function oostpoort_settings() {

 //only administrators can access this module
 if (!user_access('access administration pages')) 
 {
    return drupal_access_denied();
 }

 $form['settings_general'] = array('#type' => 'fieldset', '#title' => t('General settings'));

 $form['settings_general']['oostpoort_roles'] = array(
     '#type' => 'textarea',
     '#title' => t('Roles'),
     '#default_value' => variable_get('oostpoort_roles', ''),
     '#rows' => 1,
     '#description' => t("Enter roles with a person can have (Seperated items with commas. No space allowed).") );

  $form['map24'] = array('#type' => 'fieldset', '#title' => t('Map settings'));

  $form['map24']['addressbook_map_link'] = array(
     '#type' => 'select',
     '#title' => t('Activate map link'),
     '#default_value' => variable_get('addressbook_map_link',0),
     '#options' => array( 0 => t('No'), 1 => t('Yes') ),
     '#description' => t('Enable / Disable Activate www.map24.com fast link.'));

  $form['map24']['addressbook_map_key'] = array(
     '#type' => 'textfield',
     '#title' => t('Free www.map24.com access key'),
     '#default_value' => variable_get('addressbook_map_key', ''),
     '#description' => t("Enter access key (Visit http://www.map24.com to get a free key)"),
     '#maxlength' => '50',
     '#size' => '50');

  return system_settings_form($form);
}

// ##################################################################################
// THE END
// ##################################################################################
