<?php

/* 
**  Church Administration (oostpoort) module for drupal 
**
**  Copyright (C) 2009-2010
**  =======================
**
**  Created by wplaat
**
**  For more information visit the following website.
**  Website : http://www.plaatsoft.nl 
**
**  Or send an email to the following address.
**  Email   : info@plaatsoft.nl
**
**  This program is free software; you can redistribute it and/or modify
**  it under the terms of the GNU General Public License as published by
**  the Free Software Foundation, version 2.
**
**  This program is distributed in the hope that it will be useful,
**  but WITHOUT ANY WARRANTY; without even the implied warranty of
**  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
**  GNU General Public License for more details.
**
**  You should have received a copy of the GNU General Public License
**  along with this program; if not, write to the Free Software
**  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
*/


// Oostpoort Files store
define('OOSTPOORT_IMAGE_DIR',       'files/oostpoort');
define('OOSTPOORT_THUMBNAILS_DIR',  'files/oostpoort/thumbnails');

// Oostpoort URLs
define('OOSTPOORT_MENU',            'oostpoort');

define('OOSTPOORT_FAMILY',     		'oostpoort/family');

define('OOSTPOORT_JUBILEA_BIRTHDAY','oostpoort/jubilea/birthday');
define('OOSTPOORT_JUBILEA_MARRIED', 'oostpoort/jubilea/married');
define('OOSTPOORT_MEMBER_AGE',      'oostpoort/member/age');

define('OOSTPOORT_UPLOAD_CSV',      'oostpoort/upload/csv');
define('OOSTPOORT_UPLOAD_PICTURE',  'oostpoort/upload/picture');

define('OOSTPOORT_VISIT',           'oostpoort/visit');
define('OOSTPOORT_VISIT_ADMIN',     'oostpoort/visit/admin');


// ##################################################################################
// THE END
// ##################################################################################
